---
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    curl -u $(ASSERTIBLE_API_TOKEN_2): 'https://assertible.com/tests' > tests.json
    curl -XPOST -u $(ASSERTIBLE_API_TOKEN_1): https://assertible.com/apis/$(ASSERTIBLE_API_PROJECT)/run -d'{
      "wait": true
    }' > results.json
  displayName: 'Run Assertible Tests'
- script: |
    git clone https://github.com/prmiguel/assertible-to-junit.git
    cd assertible-to-junit
    npm i
    npm run build
    npm run add
    cd ..
    assertible-to-junit "$(cat results.json)" "$(cat tests.json)"
  displayName: Generate Junit Report
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-report.xml'
    failTaskOnFailedTests: true
    failTaskOnMissingResultsFile: true